// <auto-generated />
using System;
using ACNH_Marketplace.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ACNH_Marketplace.DataBase.Migrations
{
    [DbContext(typeof(MarketplaceContext))]
    [Migration("20200511181132_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ACNH_Marketplace.DataBase.Models.TurnipEntryFee", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("FeeType")
                        .HasColumnType("int");

                    b.Property<byte[]>("TurnipMarketHosterId")
                        .HasColumnType("varbinary(16)");

                    b.Property<byte[]>("TurnipMarketVisitorId")
                        .HasColumnType("varbinary(16)");

                    b.HasKey("Id");

                    b.HasIndex("TurnipMarketHosterId");

                    b.HasIndex("TurnipMarketVisitorId");

                    b.ToTable("TurnipEntryFees");
                });

            modelBuilder.Entity("ACNH_Marketplace.DataBase.Models.TurnipMarketHoster", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime");

                    b.Property<int>("TurnipCost")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TurnipMarketHosters");
                });

            modelBuilder.Entity("ACNH_Marketplace.DataBase.Models.TurnipMarketVisitor", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TurnipMarketVisitors");
                });

            modelBuilder.Entity("ACNH_Marketplace.DataBase.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<float>("ExchangeRating")
                        .HasColumnType("float");

                    b.Property<float>("HosterRating")
                        .HasColumnType("float");

                    b.Property<string>("InGameName")
                        .HasColumnType("text");

                    b.Property<string>("IslandName")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastActiveDate")
                        .HasColumnType("datetime");

                    b.Property<int>("Timezone")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.Property<float>("VisitorRating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ACNH_Marketplace.DataBase.Models.UserReview", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(16)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("ReviewedId")
                        .HasColumnType("int");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReviewedId");

                    b.HasIndex("ReviewerId");

                    b.ToTable("UserReviews");
                });

            modelBuilder.Entity("ACNH_Marketplace.DataBase.Models.TurnipEntryFee", b =>
                {
                    b.HasOne("ACNH_Marketplace.DataBase.Models.TurnipMarketHoster", null)
                        .WithMany("Fee")
                        .HasForeignKey("TurnipMarketHosterId");

                    b.HasOne("ACNH_Marketplace.DataBase.Models.TurnipMarketVisitor", null)
                        .WithMany("Fee")
                        .HasForeignKey("TurnipMarketVisitorId");
                });

            modelBuilder.Entity("ACNH_Marketplace.DataBase.Models.TurnipMarketHoster", b =>
                {
                    b.HasOne("ACNH_Marketplace.DataBase.Models.User", "User")
                        .WithMany("Hosts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ACNH_Marketplace.DataBase.Models.TurnipMarketVisitor", b =>
                {
                    b.HasOne("ACNH_Marketplace.DataBase.Models.User", "User")
                        .WithMany("Visits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ACNH_Marketplace.DataBase.Models.UserReview", b =>
                {
                    b.HasOne("ACNH_Marketplace.DataBase.Models.User", "Reviewed")
                        .WithMany("UserReviews")
                        .HasForeignKey("ReviewedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ACNH_Marketplace.DataBase.Models.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
