// <auto-generated/>
using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace ACNH_Marketplace.DataBase.Migrations
{
    /// <inheritdoc/>
    public partial class Initial_migration : Migration
    {
        /// <inheritdoc/>
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Users",
                columns: table => new
                {
                    Id = table.Column<Guid>(nullable: false),
                    TelegramId = table.Column<int>(nullable: false),
                    InGameName = table.Column<string>(nullable: true),
                    IslandName = table.Column<string>(nullable: true),
                    Timezone = table.Column<int>(nullable: false),
                    LastActiveDate = table.Column<DateTime>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Users", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "TurnipMarketHosters",
                columns: table => new
                {
                    Id = table.Column<Guid>(nullable: false),
                    BeginingDate = table.Column<DateTime>(nullable: false),
                    ExpirationDate = table.Column<DateTime>(nullable: false),
                    Price = table.Column<int>(nullable: false),
                    Description = table.Column<string>(nullable: true),
                    UserId = table.Column<Guid>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_TurnipMarketHosters", x => x.Id);
                    table.ForeignKey(
                        name: "FK_TurnipMarketHosters_Users_UserId",
                        column: x => x.UserId,
                        principalTable: "Users",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "TurnipMarketVisitors",
                columns: table => new
                {
                    Id = table.Column<Guid>(nullable: false),
                    PriceLowerBound = table.Column<int>(nullable: false),
                    Description = table.Column<string>(nullable: true),
                    UserId = table.Column<Guid>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_TurnipMarketVisitors", x => x.Id);
                    table.ForeignKey(
                        name: "FK_TurnipMarketVisitors_Users_UserId",
                        column: x => x.UserId,
                        principalTable: "Users",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "UserContacts",
                columns: table => new
                {
                    Id = table.Column<Guid>(nullable: false),
                    Type = table.Column<int>(nullable: false),
                    Contact = table.Column<string>(nullable: true),
                    UserId = table.Column<Guid>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_UserContacts", x => x.Id);
                    table.ForeignKey(
                        name: "FK_UserContacts_Users_UserId",
                        column: x => x.UserId,
                        principalTable: "Users",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "UserReports",
                columns: table => new
                {
                    OperationType = table.Column<int>(nullable: false),
                    OperationId = table.Column<Guid>(nullable: false),
                    Id = table.Column<Guid>(nullable: false),
                    UserId = table.Column<Guid>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_UserReports", x => new { x.OperationType, x.OperationId });
                    table.ForeignKey(
                        name: "FK_UserReports_Users_UserId",
                        column: x => x.UserId,
                        principalTable: "Users",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "UserReviews",
                columns: table => new
                {
                    Id = table.Column<Guid>(nullable: false),
                    Type = table.Column<int>(nullable: false),
                    Description = table.Column<string>(nullable: true),
                    Rating = table.Column<int>(nullable: false),
                    ReviewerId = table.Column<Guid>(nullable: false),
                    ReviewedId = table.Column<Guid>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_UserReviews", x => x.Id);
                    table.ForeignKey(
                        name: "FK_UserReviews_Users_ReviewedId",
                        column: x => x.ReviewedId,
                        principalTable: "Users",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_UserReviews_Users_ReviewerId",
                        column: x => x.ReviewerId,
                        principalTable: "Users",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "TurnipMarketEntryFees",
                columns: table => new
                {
                    Id = table.Column<Guid>(nullable: false),
                    TurnipMarketHosterId = table.Column<Guid>(nullable: true),
                    TurnipMarketVisitorId = table.Column<Guid>(nullable: true),
                    FeeType = table.Column<int>(nullable: false),
                    Description = table.Column<string>(nullable: true),
                    Count = table.Column<int>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_TurnipMarketEntryFees", x => x.Id);
                    table.ForeignKey(
                        name: "FK_TurnipMarketEntryFees_TurnipMarketHosters_TurnipMarketHoste~",
                        column: x => x.TurnipMarketHosterId,
                        principalTable: "TurnipMarketHosters",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_TurnipMarketEntryFees_TurnipMarketVisitors_TurnipMarketVisi~",
                        column: x => x.TurnipMarketVisitorId,
                        principalTable: "TurnipMarketVisitors",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_TurnipMarketEntryFees_TurnipMarketHosterId",
                table: "TurnipMarketEntryFees",
                column: "TurnipMarketHosterId");

            migrationBuilder.CreateIndex(
                name: "IX_TurnipMarketEntryFees_TurnipMarketVisitorId",
                table: "TurnipMarketEntryFees",
                column: "TurnipMarketVisitorId");

            migrationBuilder.CreateIndex(
                name: "IX_TurnipMarketHosters_UserId",
                table: "TurnipMarketHosters",
                column: "UserId");

            migrationBuilder.CreateIndex(
                name: "IX_TurnipMarketVisitors_UserId",
                table: "TurnipMarketVisitors",
                column: "UserId",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_UserContacts_UserId",
                table: "UserContacts",
                column: "UserId");

            migrationBuilder.CreateIndex(
                name: "IX_UserReports_UserId",
                table: "UserReports",
                column: "UserId");

            migrationBuilder.CreateIndex(
                name: "IX_UserReviews_ReviewedId",
                table: "UserReviews",
                column: "ReviewedId");

            migrationBuilder.CreateIndex(
                name: "IX_UserReviews_ReviewerId",
                table: "UserReviews",
                column: "ReviewerId");
        }

        /// <inheritdoc/>
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "TurnipMarketEntryFees");

            migrationBuilder.DropTable(
                name: "UserContacts");

            migrationBuilder.DropTable(
                name: "UserReports");

            migrationBuilder.DropTable(
                name: "UserReviews");

            migrationBuilder.DropTable(
                name: "TurnipMarketHosters");

            migrationBuilder.DropTable(
                name: "TurnipMarketVisitors");

            migrationBuilder.DropTable(
                name: "Users");
        }
    }
}
