// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

namespace ACNH_Marketplace.DataBase.Migrations
{
    /// <inheritdoc/>
    public partial class IsUserBanned : Migration
    {
        /// <inheritdoc/>
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<bool>(
                name: "IsBanned",
                table: "Users",
                nullable: false,
                defaultValue: false);
        }

        /// <inheritdoc/>
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "IsBanned",
                table: "Users");
        }
    }
}
