// <auto-generated />
using System;
using ACNH_Marketplace.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ACNH_Marketplace.DataBase.Migrations
{
    [DbContext(typeof(MarketplaceContext))]
    partial class MarketplaceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ACNH_Marketplace.DataBase.Models.EntryFee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("FeeType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TurnipMarketHosterId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TurnipMarketVisitorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TurnipMarketHosterId");

                    b.HasIndex("TurnipMarketVisitorId");

                    b.ToTable("EntryFees");
                });

            modelBuilder.Entity("ACNH_Marketplace.DataBase.Models.TurnipMarketHoster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BeginingDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TurnipMarketHosters");
                });

            modelBuilder.Entity("ACNH_Marketplace.DataBase.Models.TurnipMarketVisitor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("PriceLowerBound")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("TurnipMarketVisitors");
                });

            modelBuilder.Entity("ACNH_Marketplace.DataBase.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("InGameName")
                        .HasColumnType("text");

                    b.Property<string>("IslandName")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastActiveDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("TelegramId")
                        .HasColumnType("integer");

                    b.Property<int>("Timezone")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ACNH_Marketplace.DataBase.Models.UserContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Contact")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserContacts");
                });

            modelBuilder.Entity("ACNH_Marketplace.DataBase.Models.UserReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid>("ReviewedId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReviewedId");

                    b.HasIndex("ReviewerId");

                    b.ToTable("UserReviews");
                });

            modelBuilder.Entity("ACNH_Marketplace.DataBase.Models.EntryFee", b =>
                {
                    b.HasOne("ACNH_Marketplace.DataBase.Models.TurnipMarketHoster", null)
                        .WithMany("Fee")
                        .HasForeignKey("TurnipMarketHosterId");

                    b.HasOne("ACNH_Marketplace.DataBase.Models.TurnipMarketVisitor", null)
                        .WithMany("Fee")
                        .HasForeignKey("TurnipMarketVisitorId");
                });

            modelBuilder.Entity("ACNH_Marketplace.DataBase.Models.TurnipMarketHoster", b =>
                {
                    b.HasOne("ACNH_Marketplace.DataBase.Models.User", "User")
                        .WithMany("Hosts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ACNH_Marketplace.DataBase.Models.TurnipMarketVisitor", b =>
                {
                    b.HasOne("ACNH_Marketplace.DataBase.Models.User", "User")
                        .WithOne("Visits")
                        .HasForeignKey("ACNH_Marketplace.DataBase.Models.TurnipMarketVisitor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ACNH_Marketplace.DataBase.Models.UserContact", b =>
                {
                    b.HasOne("ACNH_Marketplace.DataBase.Models.User", "User")
                        .WithMany("UserContacts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ACNH_Marketplace.DataBase.Models.UserReview", b =>
                {
                    b.HasOne("ACNH_Marketplace.DataBase.Models.User", "Reviewed")
                        .WithMany("UserReviews")
                        .HasForeignKey("ReviewedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ACNH_Marketplace.DataBase.Models.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
